### ISSUE TITLE
Could not install package 'IPAddressFiltering 2.1.4'.

### ISSUE THREAD

**Issue by icnocop** [dejanstojanovic/IP-Address-Filtering#3]
Hi.

When I try to install the latest nuget package in Visual Studio 2015 Update 3, I get the following error message:

`Could not install package 'IPAddressFiltering 2.1.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by dejanstojanovic** [comment]
I think this could be because you project is not targeting the same framework version, probably lower than v4.6.1. 
There are two possible solutions:
- Set your project target framework to 4.6.1
- Fork this repo, compile to framework you use and then reference the output in your project

I hope this helped
